name: Sanity check
on:
  push:
    tags:
      - v*
    branches:
      - '*'
      - main
  pull_request:
permissions:
  contents: read
env:
  SCYLLA_ARGS: "--seeds=node1,node2 --authenticator PasswordAuthenticator --api-address 0.0.0.0"
jobs:
  sanity:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.0
          stable: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2

      - name: Setup 3-node Scylla cluster
        run: |
          sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"
          docker-compose up -d

      - name: Run tests
        run: make test

      - name: Ensure nodes are up
        run: |
          until docker compose exec node1 nodetool status; do sleep 1; done
          while [[ $(docker compose exec node1 nodetool status | grep -c ^UN) != "3" ]]; do sleep 1; done

      - name: Run integration tests
        run: make docker-integration-test
        
      - name: Stop cluster
        run: docker-compose down
